### ISSUE TITLE
Xcode 14 and BlueRSA

### ISSUE THREAD

**Issue by priore** [Kitura/Swift-JWT#109]
Incompatible version of BlueRSA dependency on Xcode 14

![swiftjwt_bluersa](https://user-images.githubusercontent.com/1537350/191619099-f0141637-d4c2-494f-a48f-629346cb708b.jpg)

**Comment by dannys42** [comment]
@priore What version of [Swift-JWT](https://github.com/Kitura/Swift-JWT) are you using?  I do not see an issue on master/3.6.201 compiling for macOS or iOS.

**Comment by priore** [comment]
I didn't have time, I replaced with other library, thanks.
