### ISSUE TITLE
Bump version to `4.0.1`

### ISSUE THREAD

**Issue by Marcocanc** [Kitura/Swift-JWT#112]
Hi, would it be possible to do a patch bump to `4.0.1` in order to include the localized error changes?

**Comment by dannys42** [comment]
Hi @Marcocanc.  I created a tag for 4.0.1.  Hopefully you're using SPM.  I'm not sure I'll be able to continue to support cocoapods as I continually run into problems trying to push pods.

**Comment by Marcocanc** [comment]
That'll do, thanks!
