### ISSUE TITLE
Update release on cocoapods

### ISSUE THREAD

**Issue by GuillaumeBourge** [Kitura/Swift-JWT#95]
I cannot install last 3.6.0 and 3.6.1 with Pods, i am lock on the 3.5.3 :(

i use  " pod 'SwiftJWT'", i already made a "pod repo update", and if i use "pod 'SwiftJWT', '3.6.1'" i get this error : 
[!] CocoaPods could not find compatible versions for pod "SwiftJWT"

there are mention of the version on https://cocoapods.org/pods/SwiftJWT
Are you sure that is upToDate ?

**Comment by dannys42** [comment]
Hi @GuillaumeBourge, we're still in the middle of migrating Kitura repos over to the Kitura org (from the IBM-Swift org), which may be causing some issues with recent versions.  Are you able to stay with 3.5.3 for a little while longer?

**Comment by GuillaumeBourge** [comment]
Hi, no problem :) can you mention the link of new repos when you will be ok please ?

**Comment by mbarnach** [comment]
Hi @GuillaumeBourge Github is doing the forward automatically, but the new URLs are Kitura instead of IBM-Swift, as you can see in this repo right now. W are trying to "adopt" the CocoaPods also, so there will be no changes hopefully there too.

**Comment by GuillaumeBourge** [comment]
I just seen the org name change ! :D

**Comment by mbarnach** [comment]
The PR #96 should fix this. When merged, a new release will be pushed on Cocoapods.

**Comment by rph8** [comment]
#96 is merged, so I think this can be closed.
